name: pocket_scat
description: goomba

version: 2.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  audioplayers: 0.14.0
  dart_random_choice: 0.0.2
  esys_flutter_share: 1.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  mockito: 4.1.1
  flutter_launcher_icons: 0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/bean.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/